wild_animal = input("pls enter a wild animal: ")
domestic_animal = input("pls enter a domestic animal: ")
adj1 = input("pls enter an adjective: ")
verb1 = input("pls enter a a continous verb: ")
liquid = input("Pls enter a liquid: ")
location = input("pls enter a place: ")
adverb = input("pls enter an adverb: ")
print(f"A {adj1} {wild_animal} was once {verb1} {liquid} at a {location}.")
print(f"He caught sight of a {domestic_animal} {verb1} {liquid} far down.")
print(f"He wanted to eat it all.\\nHe ran up to it and said very {adverb}, why are you making the {liquid} very muddy? \\nDon't you see that I am {verb1} it?")